spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://google/customerdb?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false&allowPublicKeyRetrieval=true
cloud:
  gcp:
    sql:
      instance-connection-name: ${CLOUD_SQL_CONNECTION_NAME}
    project-id: ${GOOGLE_CLOUD_PROJECT}
