steps:
  # 1: Build JAR (usa Maven Wrapper)
  - name: 'maven:3.9-eclipse-temurin-21-alpine'
    entrypoint: 'bash'
    args: ['-c', './mvnw -B -Dmaven.test.skip package']

  # 2: Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/customer-api:$COMMIT_SHA', '.']

  # 3: Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/customer-api:$COMMIT_SHA']

  # 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'customer-api'
      - '--image=gcr.io/$PROJECT_ID/customer-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated=false' # requiere JWT
      - '--update-secrets=JWT_SECRET=projects/$PROJECT_ID/secrets/jwt-secret:latest'
      - '--set-env-vars'
      - |
        SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/customerdb,
        SPRING_DATASOURCE_USERNAME=api_user,
        SPRING_DATASOURCE_PASSWORD=__SECRET_VAR__=CUSTOMER_DB_PWD,
        SPRING_PROFILES_ACTIVE=prod

images:
  - 'gcr.io/$PROJECT_ID/customer-api:$COMMIT_SHA'
